{% set version = "1.9.3" %}

package:
  name: argcomplete
  version: {{ version }}

source:
  fn: argcomplete-{{ version }}.tar.gz
  url:  https://pypi.io/packages/source/a/argcomplete/argcomplete-{{ version }}.tar.gz
  sha256: d97b7f3cfaa4e494ad59ed6d04c938fc5ed69b590bd8f53274e258fb1119bd1b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  # disabled due to https://github.com/conda/conda-build/issues/2627 
  #noarch: python
requirements:
  build:
    - setuptools 

  run:
    - python

test:
  imports:
    - argcomplete
  commands:
    - register-python-argcomplete -h

about:
  home: https://github.com/kislyuk/argcomplete
  license: Apache 2.0
  summary: 'Bash tab completion for argparse'
  license_family: Apache
  license_file: LICENSE.rst
  doc_url: https://argcomplete.readthedocs.io
  dev_url: https://github.com/kislyuk/argcomplete

extra:
  recipe-maintainers:
    - asmeurer
