{% set name = "argcomplete" %}
{% set version = "3.3.0" %}

package:
  name: argcomplete
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/argcomplete-{{ version }}.tar.gz
  sha256: fd03ff4a5b9e6580569d34b273f741e85cd9e072f3feeeee3eba4891c70eda62

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.8
    - setuptools >=67.7.2
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - argcomplete

about:
  home: https://github.com/kislyuk/argcomplete
  license: Apache-2.0
  summary: Bash tab completion for argparse
  license_family: Apache
  license_file:
    - LICENSE.rst
    - NOTICE
  doc_url: https://argcomplete.readthedocs.io
  dev_url: https://github.com/kislyuk/argcomplete

extra:
  recipe-maintainers:
    - asmeurer
    - xylar
