{% set name = "argcomplete" %}
{% set version = "3.0.5" %}

package:
  name: argcomplete
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/argcomplete-{{ version }}.tar.gz
  sha256: fe3ce77125f434a0dd1bffe5f4643e64126d5731ce8d173d36f62fa43d6eb6f7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - argcomplete

about:
  home: https://github.com/kislyuk/argcomplete
  license: Apache-2.0
  summary: Bash tab completion for argparse
  license_family: Apache
  license_file:
    - LICENSE.rst
    - NOTICE
  doc_url: https://argcomplete.readthedocs.io
  dev_url: https://github.com/kislyuk/argcomplete

extra:
  recipe-maintainers:
    - asmeurer
    - xylar
