{% set version = "1.9.3" %}

package:
  name: argcomplete
  version: {{ version }}

source:
  fn: argcomplete-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/8b/54/4a431fe1dfac0d9ae9adc725d2fe543fad07fb7d87f15bd732ba63672bb4/argcomplete-1.9.3.tar.gz
  md5: 0d0c71c96a932977f60567566a6f5eac

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
#  noarch: python

requirements:
  build:
    - setuptools 

  run:
    - python

test:
  imports:
    - argcomplete
  commands:
    - register-python-argcomplete -h

about:
  home: https://github.com/kislyuk/argcomplete
  license: Apache 2.0
  summary: 'Bash tab completion for argparse'
  license_family: Apache
  license_file: LICENSE.rst
  doc_url: https://argcomplete.readthedocs.io
  dev_url: https://github.com/kislyuk/argcomplete

extra:
  recipe-maintainers:
    - asmeurer
