{% set name = "argcomplete" %}
{% set version = "3.5.1" %}

package:
  name: argcomplete
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/argcomplete-{{ version }}.tar.gz
  sha256: eb1ee355aa2557bd3d0145de7b06b2a45b0ce461e1e7813f5d066039ab4177b4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.8
    - setuptools >=67.7.2
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - argcomplete

about:
  home: https://github.com/kislyuk/argcomplete
  license: Apache-2.0
  summary: Bash tab completion for argparse
  license_family: Apache
  license_file:
    - LICENSE.rst
    - NOTICE
  doc_url: https://argcomplete.readthedocs.io
  dev_url: https://github.com/kislyuk/argcomplete

extra:
  recipe-maintainers:
    - asmeurer
    - xylar
