{% set name = "argcomplete" %}
{% set version = "3.0.8" %}

package:
  name: argcomplete
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/argcomplete-{{ version }}.tar.gz
  sha256: b9ca96448e14fa459d7450a4ab5a22bbf9cee4ba7adddf03e65c398b5daeea28

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    # this avoids the need to include importlib-metadata
    - python >=3.7

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - argcomplete

about:
  home: https://github.com/kislyuk/argcomplete
  license: Apache-2.0
  summary: Bash tab completion for argparse
  license_family: Apache
  license_file:
    - LICENSE.rst
    - NOTICE
  doc_url: https://argcomplete.readthedocs.io
  dev_url: https://github.com/kislyuk/argcomplete

extra:
  recipe-maintainers:
    - asmeurer
    - xylar
